### ISSUE TITLE
[JOSS REVIEW] Add contributing guidelines

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#10]
As an open source project you should make sure to add some documentation on how to contribute to the project, see https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
Thanks for this issue @finsberg I have added a "contributing" file in the docs directory and a section in the readme. If you are happy with the PR that was just merged, we can close this issue.

**Comment by finsberg** [comment]
Looks good!
