### ISSUE TITLE
[JOSS REVIEW] Problem running `examples/EMG_streaming.py`

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#18]
When running the `EMG_streaming.py` example I get the following error
```
python EMG_streaming.py
Traceback (most recent call last):
  File "/Users/finsberg/local/src/biosiglive/examples/EMG_streaming.py", line 22, in <module>
    from examples.custom_interface import MyInterface
ModuleNotFoundError: No module named 'examples'
```
Changing the line 
```python
from examples.custom_interface import MyInterface
```
to 
```python
from custom_interface import MyInterface
```
fixes the problem. Perhaps I am doing something wrong?

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
You did right, the "example." is an artifact in the last PR. I removed this in my last PR and had updated the package on PIP but conda take some time to update. For next runs please be sure to be in version 2.0.2.
