### ISSUE TITLE
[JOSS REVIEW] Add documentation page

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#6]
The only documentation I could find about this project is within the README file. 

I think this project deserves a proper documentation hosted at e.g [GitHub pages](https://pages.github.com) or [Read the docs](https://readthedocs.org). This would make the project much more digestible for more users. Furthermore, you could also host API documentation which you could generate using [Sphinx API doc](https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html) on this page.

On such a documentation page, you should also add separate pages with the examples.

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
@finsberg I created a documentation for the library (https://biosiglive.readthedocs.io/). It is a first version and therefore I will update it depends on the users needs. But if it suits you for now we may close this issue. Thanks.

**Comment by finsberg** [comment]
Looks very good!
