### ISSUE TITLE
[JOSS REVIEW] Add `biosiglive` to pypi

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#7]
I think it is great that you have added `biosiglive` to conda-forge, but for user that don't use conda it would also be great if you could add it to [pypi](https://pypi.org)

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
It's done on in the PR #12 that I just merged. Indeed I use conda by default but it is preferable that the package is on both thanks! 
I took the opportunity to delete the setup.py and requirements.txt files. So I think we can close this issue and the #5.

**Comment by finsberg** [comment]
Great!
