### ISSUE TITLE
[JOSS REVIEW] Add CI to run tests

### ISSUE THREAD

**Issue by finsberg** [pyomeca/biosiglive#9]
I see that you have a lot of tests, which is great! However, to make sure that the tests continue to pass you should also set up some continuous integration that runs the tests on every push and pull request to the main branch, see e.g https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

This is related to https://github.com/openjournals/joss-reviews/issues/5091

**Comment by aceglia** [comment]
@finsberg I added some github ation workflows. One to check if the code is linted with black and the other to run tests. Obviously tests that needs connection to devices are not run as it is not possible to establish any connection.  
The workflow is launched at each PR. If it suites you we can close this issue. Thanks for this issue which will smooth the contribution workflow.
